d = float(input('Digite a distância em metros: '))
print('A medida de {}m corresponde a: '.format(d))
print(d/1000,'km')
print(d/100,'hm')
print(d/10,'dam')
print('{:.0f}dm'.format(d*10))
print('{:.0f}cm'.format(d*100))
print('{:.0f}mm'.format(d*1000))
